const users = [
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 1,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:' doe1' ,
        email:'johndoa3323@gmail.com',
        queries: 2,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 3,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 4,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 5,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 6,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 7,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 8,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 9,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 10,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 11,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 12,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 13,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 14,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 15,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 16,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 17,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 18,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 19,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 20,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 21,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 22,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 23,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 24,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 25,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 26,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 27,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 28,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 29,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 30,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 31,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 32,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 33,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 34,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 35,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 36,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 37,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 38,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 39,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 40,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 41,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 42,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 43,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 44,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 45,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 46,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 47,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 48,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 49,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 50,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 51,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 52,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 53,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 54,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 55,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    {
        img:'/profile_user.jpg',
        name:'John doe1' ,
        email:'johndoa@gmail.com',
        queries: 56,
        avgresponsetime:'3 min 30 secs',
        lastseen:'online',
        amount:'Monthly',
    },
    
    
    
    
];
export const getUsers = function(page, limit){
    let array = [];
    for (let i = (page - 1)* limit; i < (page * limit) && users[i]; i++) {
        array.push(users[i]);
        
    }
    
    return array;
    
}
export const getClient = function(Clientpage, Clientlimit){
    let clientarray = [];
    for (let i = (Clientpage - 1)* Clientlimit; i < (Clientpage * Clientlimit) && users[i]; i++) {
        clientarray.push(users[i]);
        
    }
    
    return clientarray;
    
}

export const getLength = function () {
    return users.length;
}